from: markdown
to: pdf

input-files:
  - report/10-student-outcome.md
  - report/12-startup-profile.md
  - report/13-solution-profile.md

file-scope: true
resource-path: [".", "report/assets"]
output-file: build/project-report.pdf

pdf-engine: weasyprint
css:
  - css/report.css

bibliography: references.bib
csl: config/apa.csl
citeproc: true

toc: true
toc-depth: 3
number-sections: true
syntax-highlighting: tango
