input-files:
  - config/metadata.yaml
  - report/front-matter/01-version-history.md
  - report/front-matter/02-collaboration-insights.md
  - report/front-matter/03-toc.md
  - report/10-student-outcome.md

file-scope: true
resource-path: [".", "report/assets"]
output-file: build/project-report.pdf

pdf-engine: lualatex
template: templates/eisvogel

bibliography: references.bib
csl: config/apa.csl
citeproc: true

toc: false
number-sections: true
syntax-highlighting: tango
